version: '2'
services:
  world0data:
    image: busybox
    volumes:
      - /minecraft
    command: 'true'
  world0server:
    image: nimmis/spigot
    volumes_from:
      - world0data
    environment:
      - EULA=true
  world1data:
    image: busybox
    volumes:
      - /minecraft
    command: 'true'
  world1server:
    image: nimmis/spigot
    volumes_from:
      - world1data
    environment:
      - EULA=true
  world2data:
    image: busybox
    volumes:
      - /minecraft
    command: 'true'
  world2server:
    image: nimmis/spigot
    volumes_from:
      - world2data
    environment:
      - EULA=true
  bungeecorddata:
    image: busybox
    volumes:
      - /bungeecord
    command: 'true'
  bungeecordserver:
    image: rehf27/bungeecord
    ports:
      - 25577:25577
    volumes_from:
      - bungeecorddata
    environment:
      - EULA=true
    links:
      - world0server
      - world1server
      - world2server
